# Generated by Django 3.1.7 on 2021-04-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collegemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=250)),
                ('ext_year', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'college',
            },
        ),
        migrations.CreateModel(
            name='collegeteammodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namee', models.CharField(max_length=50)),
                ('datee', models.CharField(max_length=50)),
                ('COLLEGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.collegemodel')),
            ],
            options={
                'db_table': 'collegeteam',
            },
        ),
        migrations.CreateModel(
            name='eventmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('descri', models.CharField(max_length=250)),
                ('etype', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='loginmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('pwd', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='notificationmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=50)),
                ('datee', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='sports_catmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sports_cate',
            },
        ),
        migrations.CreateModel(
            name='studentmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=250)),
                ('house', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=50)),
                ('sem', models.CharField(max_length=50)),
                ('gen', models.CharField(max_length=50)),
                ('COLLEGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.collegemodel')),
                ('LID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.loginmodel')),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=250)),
                ('ph', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=250)),
                ('desi', models.CharField(max_length=50)),
                ('utype', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('COLLEGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.collegemodel')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.loginmodel')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='team_member_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentmodel')),
                ('TEAM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.collegeteammodel')),
            ],
            options={
                'db_table': 'team_member',
            },
        ),
        migrations.CreateModel(
            name='staffmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('gen', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('COLLEGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.collegemodel')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.loginmodel')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='sports_profilemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentmodel')),
            ],
            options={
                'db_table': 'sports_profile',
            },
        ),
        migrations.CreateModel(
            name='schedulemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_from', models.CharField(max_length=50)),
                ('time_to', models.CharField(max_length=50)),
                ('datee', models.CharField(max_length=50)),
                ('COLLEGETEAM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.collegeteammodel')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.CreateModel(
            name='participantmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EVENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.eventmodel')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentmodel')),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.CreateModel(
            name='nutritionmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descri', models.CharField(max_length=250)),
                ('COLLEGE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.collegeteammodel')),
            ],
            options={
                'db_table': 'nutrition',
            },
        ),
        migrations.CreateModel(
            name='nutritionallocationmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('datee', models.CharField(max_length=50)),
                ('NUTRITION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.nutritionmodel')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentmodel')),
            ],
            options={
                'db_table': 'nutrition_allocation',
            },
        ),
        migrations.CreateModel(
            name='msg_nutitionnist_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datee', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=250)),
                ('mtype', models.CharField(max_length=50)),
                ('NUTRITION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.nutritionmodel')),
            ],
            options={
                'db_table': 'msg_nutitionist',
            },
        ),
        migrations.CreateModel(
            name='motivationmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=50)),
                ('contnt_type', models.CharField(max_length=50)),
                ('desci', models.CharField(max_length=250)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staffmodel')),
            ],
            options={
                'db_table': 'motivation',
            },
        ),
        migrations.CreateModel(
            name='gallerymodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=250)),
                ('datee', models.CharField(max_length=20)),
                ('desi', models.CharField(max_length=50)),
                ('EVENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.eventmodel')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staffmodel')),
            ],
            options={
                'db_table': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='eventorgizermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250)),
                ('ph', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=250)),
                ('desi', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.loginmodel')),
            ],
            options={
                'db_table': 'event_orgizer',
            },
        ),
        migrations.CreateModel(
            name='complaintmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt', models.CharField(max_length=250)),
                ('datee', models.CharField(max_length=50)),
                ('reply', models.CharField(max_length=250)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentmodel')),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.AddField(
            model_name='collegeteammodel',
            name='STAFF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staffmodel'),
        ),
        migrations.AddField(
            model_name='collegemodel',
            name='LID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.loginmodel'),
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
                ('datee', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentmodel')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usermodel')),
            ],
            options={
                'db_table': 'chatuser',
            },
        ),
        migrations.CreateModel(
            name='assign_cate_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('SPORTS_CATE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sports_catmodel')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staffmodel')),
            ],
            options={
                'db_table': 'assign_cat',
            },
        ),
    ]
